# -*- coding: utf-8 -*-
"""duygu_adası .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-utdhcO8nxjjtMCsFzyUkN_2qJrXoEu7

# Ters Yüz Duygu Adası Oynu : 😂 😞 😱
Oyunumuz, taş kağıt makas oyunu formatında olan bir oyundur.

Bu duygular, animasyonun içeriğiyle uygun olarak çocukluğumuzda ortaya çıkan ilk üç  duygumuzdur: Neşe, Korku ve Üzüntü.

**Kurallarımız**:

 * Neşe, kahkahasıyla üzüntüyü dağıtır. (kazanır)
 * Korku, çığlığıyla  neşeyi  bastırır. (kazanır)
 * Üzüntü, gözyaşıyla korkuyu boğar.   (kazanır)


 - Oyun, 3 round’dan oluşuyor ve 2 round kazanan oyunun kazananı oluyor.
 - Oyun, bilgisayar ve oyuncu oynamaya devam etmek istediği sürece devam ediyor.
 - Oyuna devam edilmesi halinde, round sayısı sıfırlanıyor ve oyun sayısı birer artarak devam ediyor.
"""

import random

duygular = ["neşe", "korku", "üzüntü"]
liste = ["evet", "hayır"]
oyun_sayisi = 0
oyuncunun_skoru = 0
bilgisayar_skoru = 0
raunt_sayisi = 0

def print_welcome_message():
    print("""Hoş geldiniz! Bu oyun,'neşe', 'korku'
             ve 'üzüntü' duyguları
             üzerinden oynanır.""")
    print("""Oyun turları üç seçenekten oluşur:
             oyuncu kazanabilir,
             bilgisayar kazanabilir
             veya beraberlik olabilir.""")
    print(      "ÜSTÜNLÜKLER")
    print("Neşe, kahkahasıyla üzüntüyü dağıtır.")
    print( "Korku, çığlığıyla  neşeyi  bastırır.")
    print( "Üzüntü, gözyaşıyla korkuyu boğar.")
    print("İlk iki turu kazanan oyunu kazanır.")
    print("Oyunun geliştiricisi: Büşra ALPAY")

def duygu_secim():
    global oyuncunun_skoru, bilgisayar_skoru, raunt_sayısı
    oyuncunun_skoru = 0
    bilgisayar_skoru = 0
    raunt_sayisi = 0

    while oyuncunun_skoru < 2 and bilgisayar_skoru < 2:
        while True:
            oyuncunun_hamlesi = input(f"Lütfen bir duygu seç ({', '.join(duygular)}): ").strip().lower()
            if oyuncunun_hamlesi in duygular:
                break
            else:
                print("Lütfen, listedeki duygulardan birini seçin.")

        bilgisayarın_hamlesi = random.choice(duygular)
        print("Oyuncu:", oyuncunun_hamlesi.capitalize())
        print("Bilgisayar:", bilgisayarın_hamlesi.capitalize())

        if oyuncunun_hamlesi == bilgisayarın_hamlesi:
            print("Aynı duygudayız; BERABERLİK")
            raunt_sayisi += 1
        elif (oyuncunun_hamlesi == 'neşe' and bilgisayarın_hamlesi == 'üzüntü') or \
             (oyuncunun_hamlesi == 'korku' and bilgisayarın_hamlesi == 'neşe') or \
             (oyuncunun_hamlesi == 'üzüntü' and bilgisayarın_hamlesi == 'korku'):
            print("KAZANAN OYUNCU")
            oyuncunun_skoru += 1
            raunt_sayisi += 1
        else:
            print("KAZANAN BİLGİSAYAR")
            bilgisayar_skoru += 1
            raunt_sayisi += 1

        print("Oyuncu Skoru:", oyuncunun_skoru)
        print("Bilgisayar Skoru:", bilgisayar_skoru)
        print(f"Oyun: {oyun_sayisi}, Raunt: {raunt_sayisi}".title())

def oyun_baslat():
    global oyun_sayisi
    while True:
        oyun_sayisi += 1
        oyuncu_oyna = input("Benimle oyun mu oynamak istiyorsun? [evet/hayır]: ").strip().lower()
        if oyuncu_oyna == 'hayır':
            print("Bugün oyun oynamak için iyi bir gün değil, sanırım.")
            break

        bilgisayar_oyna = random.choice(liste)
        if oyuncu_oyna == 'evet' and bilgisayar_oyna == 'hayır':
            print("Üzgünüm; Halletmem gereken işler var.Tekrar dener misin?")
            break

        if bilgisayar_oyna == 'evet' and oyuncu_oyna == 'evet':

            print("Oyun başlıyor. İyi olan kazansın; bol şans!")
            duygu_secim()

        if oyuncunun_skoru == 2:
            print("Tebrikler! Duyguları seçmek konusunda iyisin. Oyunun SEN KAZANDIN!" , flush=True)
            while True:
                oyuncu_tekrar_oyna = input("Tekrar oynamak ister misin? [evet/hayır]: ").strip().lower()
                if oyuncu_tekrar_oyna in liste:
                    if oyuncu_tekrar_oyna == 'evet':
                        print("Hadi baştan başlayalım.")
                        oyun_sayisi += 1
                        duygu_secim()
                    else:
                        print("Oyun için teşekkürler. Tekrar görüşmek üzere.")
                        return
                else:
                    print("Lütfen, 'evet' veya 'hayır' seçeneklerinden birini yazın.")

        if bilgisayar_skoru == 2:
            print("Sonucun böyle olacağı belliydi. Oyunu BEN KAZANDIM. Oyunu BEN KAZANDIM!" , flush=True)
            while True:
                oyuncu_tekrar_oyna = input("Tekrar oynamak ister misin? [evet/hayır]: ").strip().lower()
                bilgisayar_tekrar_oyna = random.choice(liste)
                if oyuncu_tekrar_oyna in liste:
                    if bilgisayar_tekrar_oyna == 'evet':
                        if oyuncu_tekrar_oyna == 'hayır':
                            print("Sanırım kaybettiğin oyunu yeniden oynamak hiç cazip gelmiyor.")
                            return
                        else:
                             print("Hadi baştan başlayalım.")
                             oyun_sayisi += 1
                             duygu_secim()

                    elif bilgisayar_tekrar_oyna == 'hayır':
                         if oyuncu_tekrar_oyna == 'hayır':
                            print("Oyun için teşekkürler. Tekrar görüşmek üzere.")
                            break
                         else:
                            print("Tekrar oynamak istemiyorum. Biraz dinleneceğim.")
                         return
                else:
                    print("Lütfen, 'evet' veya 'hayır' seçeneklerinden birini yazın.")

if __name__ == "__main__":
    print_welcome_message()
    oyun_baslat()
